<script setup lang="ts">
import { onMounted, ref } from 'vue'
import ProductCard from '../components/ProductCard.vue'
import { listCategories, listProducts } from '../api/products'
import type { Category, Product } from '../types'
const products = ref<Product[]>([]), categories = ref<Category[]>([])
const q = ref(''), category = ref(''), page = ref(1), lastPage = ref(1), loading = ref(false), error = ref('')
async function load(reset = false) { if (reset) page.value = 1; loading.value = true; error.value = ''; try { const result = await listProducts({ q: q.value || undefined, category: category.value || undefined, page: page.value }); products.value = result.data; lastPage.value = result.last_page || 1 } catch { error.value = '商品加载失败，请稍后重试' } finally { loading.value = false } }
async function changePage(next: number) { page.value = next; await load(); window.scrollTo({ top: 0, behavior: 'smooth' }) }
onMounted(async () => { await Promise.all([load(), listCategories().then(r => categories.value = r.data).catch(() => undefined)]) })
</script>
<template><div class="mx-auto max-w-7xl px-4 py-12 sm:px-6"><section class="mb-10 rounded-3xl p-8 glass sm:p-12"><p class="mb-3 text-sm font-semibold uppercase tracking-[.3em] text-fuchsia-300">Digital Marketplace</p><h1 class="max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">发现优质<span class="bg-gradient-to-r from-fuchsia-400 to-indigo-400 bg-clip-text text-transparent">数字商品</span></h1><p class="mt-5 max-w-2xl text-zinc-400">安全支付，即时交付。精选数字资源，让创意与效率触手可及。</p></section><form class="mb-8 grid gap-3 rounded-2xl p-4 glass sm:grid-cols-[1fr_220px_auto]" @submit.prevent="load(true)"><input v-model="q" class="field" placeholder="搜索商品…" /><select v-model="category" class="field" @change="load(true)"><option value="">全部分类</option><option v-for="item in categories" :key="item.id" :value="item.slug">{{ item.name }}</option></select><button class="btn-primary" :disabled="loading">搜索</button></form><p v-if="error" class="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300">{{ error }}</p><div v-else-if="loading" class="grid place-items-center py-28 text-zinc-400">正在加载商品…</div><div v-else-if="products.length" class="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><ProductCard v-for="product in products" :key="product.id" :product="product" /></div><div v-else class="rounded-2xl py-24 text-center glass"><p class="text-xl font-semibold">没有找到商品</p><p class="mt-2 text-zinc-500">换个关键词或分类试试吧</p></div><div v-if="lastPage > 1" class="mt-10 flex items-center justify-center gap-3"><button class="rounded-xl border border-white/10 px-4 py-2 disabled:opacity-30" :disabled="page<=1" @click="changePage(page-1)">上一页</button><span class="text-sm text-zinc-400">第 {{ page }} / {{ lastPage }} 页</span><button class="rounded-xl border border-white/10 px-4 py-2 disabled:opacity-30" :disabled="page>=lastPage" @click="changePage(page+1)">下一页</button></div></div></template>
