<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { createPayment, getOrder } from '../api/payment'
import type { Order } from '../types'
const route = useRoute(), order = ref<Order | null>(null), loading = ref(true), paying = ref(false), error = ref('')
const money = (value: number) => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(value)
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '暂无'
const statusText = (status?: string) => ({ pending: '待支付', paid: '已支付', processing: '处理中', delivered: '已交付', completed: '已完成', cancelled: '已取消', failed: '失败' }[status || ''] || status || '未知')
async function pay() { if (!order.value) return; paying.value = true; error.value = ''; try { const result = await createPayment({ order_no: order.value.order_no, description: order.value.description || undefined }); window.location.href = result.payment_order.payment_url } catch { error.value = '创建支付失败' } finally { paying.value = false } }
onMounted(async () => { try { order.value = (await getOrder(String(route.params.orderNo))).order } catch { error.value = '订单详情加载失败' } finally { loading.value = false } })
</script>
<template><div class="mx-auto max-w-4xl px-4 py-12 sm:px-6"><div v-if="loading" class="py-24 text-center text-zinc-400">正在加载订单…</div><div v-else-if="order" class="space-y-6"><div class="rounded-3xl p-7 glass sm:p-9"><div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-sm text-zinc-500">订单号</p><h1 class="mt-1 break-all text-2xl font-bold">{{ order.order_no }}</h1><p class="mt-3 text-sm text-zinc-400">创建于 {{ date(order.created_at) }}</p></div><span class="w-fit rounded-full bg-fuchsia-500/10 px-4 py-2 text-sm font-medium text-fuchsia-300">{{ statusText(order.status) }}</span></div><div class="my-7 h-px bg-white/10"></div><div class="grid gap-5 sm:grid-cols-3"><div><p class="text-sm text-zinc-500">商品</p><p class="mt-1 font-medium">{{ order.product?.name || order.product_name || '数字商�品' }}</p></div><div><p class="text-sm text-zinc-500">金额</p><p class="mt-1 text-xl font-bold">{{ money(order.amount) }}</p></div><div><p class="text-sm text-zinc-500">交付状态</p><p class="mt-1 font-medium">{{ statusText(order.delivery_status) }}</p></div></div><button v-if="order.status === 'pending'" class="btn-primary mt-8" :disabled="paying" @click="pay">{{ paying ? '跳转支付中…' : '继续支付' }}</button><p v-if="error" class="mt-4 text-sm text-red-300">{{ error }}</p></div><section class="rounded-3xl p-7 glass sm:p-9"><h2 class="text-xl font-bold">交付内容</h2><p v-if="!order.cards?.length" class="mt-5 rounded-xl bg-white/5 p-5 text-zinc-400">商品尚未交付。支付成功后，交付内容会显示在这里。</p><div v-else class="mt-5 space-y-3"><div v-for="card in order.cards" :key="card.id" class="rounded-xl border border-white/10 bg-zinc-950/60 p-4"><div class="flex items-center justify-between gap-3"><span class="text-xs text-zinc-500">卡密 / 数字内容</span><span class="text-xs text-emerald-300">{{ card.status || '已交付' }}</span></div><code class="mt-3 block break-all whitespace-pre-wrap text-sm text-zinc-200">{{ card.code || card.content }}</code></div></div></section></div><p v-else class="rounded-2xl p-8 text-center text-red-300 glass">{{ error || '未找到订单' }}</p></div></template>
