<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listOrders } from '../api/payment'
import type { Order } from '../types'
const orders = ref<Order[]>([]), loading = ref(true), error = ref('')
const money = (value: number) => new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format(value)
const date = (value: string) => new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value))
const statusText = (status: string) => ({ pending: '待支付', paid: '已支付', processing: '处理中', delivered: '已交付', completed: '已完成', cancelled: '已取消', failed: '失败' }[status] || status)
onMounted(async () => { try { orders.value = (await listOrders()).orders } catch { error.value = '订单加载失败，请稍后重试' } finally { loading.value = false } })
</script>
<template><div class="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div class="mb-8"><h1 class="text-3xl font-bold">我的订单</h1><p class="mt-2 text-zinc-400">查看支付进度与数字商品交付状态</p></div><div v-if="loading" class="py-24 text-center text-zinc-400">正在加载订单…</div><p v-else-if="error" class="rounded-2xl p-6 text-red-300 glass">{{ error }}</p><div v-else-if="orders.length" class="space-y-4"><RouterLink v-for="order in orders" :key="order.id" :to="`/orders/${order.order_no}`" class="block rounded-2xl p-5 glass transition hover:border-fuchsia-400/40 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-3"><h2 class="font-semibold">{{ order.product?.name || order.product_name || '数字商品订单' }}</h2><span class="rounded-full bg-fuchsia-500/10 px-2.5 py-1 text-xs text-fuchsia-300">{{ statusText(order.status) }}</span></div><p class="mt-2 text-sm text-zinc-500">订单号：{{ order.order_no }}</p><p class="mt-1 text-sm text-zinc-500">{{ date(order.created_at) }}</p></div><div class="sm:text-right"><p class="text-xl font-bold text-white">{{ money(order.amount) }}</p><p class="mt-1 text-sm text-zinc-400">查看详情 →</p></div></div></RouterLink></div><div v-else class="rounded-3xl py-24 text-center glass"><p class="text-xl font-semibold">暂时没有订单</p><RouterLink to="/" class="mt-4 inline-block text-fuchsia-300">去逛逛商品 →</RouterLink></div></div></template>
